feat: added launcher language option
goatcorp/FFXIVQuickLauncher pull request #298
Opened 2020-10-31 06:15 UTC by Aireil

Not sure how I feel about the LauncherLanguage.cs. I used the same idea as the client language, but there were some differences that required it.
There is probably a better way to do this; I'm open to any feedback.

2020-12-06 10:48 UTC, goaaats requested changes

2020-12-06 10:48 UTC, goaaats commented on XIVLauncher/App.config
> +            <setting name="LauncherLanguage" serializeAs="String">
We aren't using these settings anymore - you don't have to add them when added to LauncherSettingsV3. They're just here for compatibility.

2020-12-06 12:58 UTC, Aireil commented
Removed the legacy settings and added a notice concerning the need to restart the launcher.

![XIVLauncher_2020-12-06_13-57-39](https://user-images.githubusercontent.com/33433913/101280731-095e5d00-37cb-11eb-8c0b-7e90431c27d2.png)

2020-12-08 09:09 UTC, goaaats approved these changes

2020-12-08 09:09 UTC, merged